[client]
showErrorDetails = false

[server]
enableStaticServing = true

[theme]
base = "light"
primaryColor = "#3B82F6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F8F9"
textColor = "#172B4D"
font = "sans serif"
headingFontSizes = ["22px", "17px", "15px", "14px", "13px", "12px"]
headingFontWeights = [700, 600, 500, 500, 400, 400]

[theme.sidebar]
backgroundColor = "#1d2125"
secondaryBackgroundColor = "#282e33"
textColor = "#c9d1d9"
primaryColor = "#4c9aff"
